name: "[00] 1password Update Credentials"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform - Deploy Kubernetes Single Cloud"]
    types:
      - completed
env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASSWORD_SERVICE_ACCOUNT_TOKEN }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ONEPASSWORD_JENKINS_ITEM: "[Lab] Jenkins (local)"
  ONEPASSWORD_ARGOCD_ITEM: "[Lab] ArgoCD (local)"
  ONEPASSWORD_VAULT: "Temporary"

jobs:
  verify-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Secret
        run: |
          echo "1PASSWORD_SERVICE_ACCOUNT_TOKEN: ${OP_SERVICE_ACCOUNT_TOKEN:0:4}****"
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:4}****"
  onePassword-credential-update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kubectl
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/kubectl.sh | sh

      - name: Set up Cluster Access Credentials
        run: |
          aws s3 cp "s3://terragrunt-output/dev/azure/Japan West/kubeconfig" ~/.kube/config

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2
        with:
          version: 2.22.0

      - name: Update 1Password Items
        run: |
          argocd_init_password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          jenkins_init_password=$(kubectl get secret jenkins -n jenkins -o yaml | yq '.data."jenkins-admin-password"' | base64 --decode)
          op item edit "$ONEPASSWORD_JENKINS_ITEM" --vault="$ONEPASSWORD_VAULT" "password=$jenkins_init_password"
          op item edit "$ONEPASSWORD_ARGOCD_ITEM" --vault="$ONEPASSWORD_VAULT" "password=$argocd_init_password"
