name: "[2.0] Velero - Backup & Restore"
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Your Action"
        required: true
        default: "backup"
        type: choice
        options:
          - backup
          - restore
          - reconcile
      cloud_provider:
        description: "Choose Cloud Provider"
        required: false
        default: "aws"
        type: choice
        options:
          - azure
          - aws
          - gcp
      region_aws:
        description: "Choose Region for EKS"
        required: false
        default: "us-east-1"
        type: choice
        options:
          - us-east-1
          - us-west-2
          - ap-east-1
      region_azure:
        description: "Choose Region for AKS"
        required: false
        default: "Japan West"
        type: choice
        options:
          - East US
          - West US 2
          - Japan West
      cluster_name:
        description: "Pick A Cluster Name"
        required: false
        default: "TESTPROJECT-DEV-GENERAL-00"
        type: choice
        options:
          - TESTPROJECT-DEV-GENERAL-00
      restored_version:
        description: "Choose A Version To Restore (First 10 latest)"
        required: false
        default: "testproject-dev-general-00-2025.12.23-02.25.18"
        type: choice
        options:
          - testproject-dev-general-00-2025.12.23-02.25.18
          - testproject-dev-general-00-2025.12.20-05.04.22
          - test4
          - test2
          - test
env:
  GH_TOKEN: ${{ secrets.PAT_GITHUB }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ github.event.inputs.cloud_provider == 'aws' && github.event.inputs.region_aws || github.event.inputs.cloud_provider == 'azure' && github.event.inputs.region_azure }}
jobs:
  verify-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Secret
        run: |
          echo "GITHUB_PAT_TOKEN: ${GH_TOKEN:0:4}****"
          echo "ARM_TENANT_ID: ${ARM_TENANT_ID:0:4}****"
          echo "ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID:0:4}****"
          echo "ARM_CLIENT_ID: ${ARM_CLIENT_ID:0:4}****"
          echo "ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET:0:4}****"
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:4}****"
          echo "HCP_CLIENT_ID: ${HCP_CLIENT_ID:0:4}****"
          echo "HCP_CLIENT_SECRET: ${HCP_CLIENT_SECRET:0:4}****"
      - name: Verify Input
        run: |
          echo "Action: ${{ github.event.inputs.action }}"
          echo "Cloud Provider: ${{ github.event.inputs.cloud_provider }}"
          echo "Region: $REGION"
  backup-restore-k8s-cloud-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Access Cluster with $KUBECONFIG
        if: ${{ github.event.inputs.action != 'reconcile' }}
        run: |
          aws eks update-kubeconfig --name ${{ github.event.inputs.cluster_name }}  --region $REGION
      - name: Reconcile to Update the Cluster Name
        if: ${{ github.event.inputs.action == 'reconcile' }}
        run: |
          chmod +x "script/2.velero--backup-and-restore/reconcile.sh"
          ./script/2.velero--backup-and-restore/reconcile.sh $GITHUB_REPOSITORY
      - name: Install Velero CLI
        if: ${{ github.event.inputs.action != 'reconcile' }}
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/velero_cli.sh | bash
      - name: Velero Fully Backup (Include Volumes)
        if: ${{ github.event.inputs.action == 'backup' }}
        run: |
          chmod +x "script/2.velero--backup-and-restore/backup.sh"
          ./script/2.velero--backup-and-restore/backup.sh "${{ github.event.inputs.cluster_name }}"
          chmod +x "script/2.velero--backup-and-restore/reconcile.sh"
          ./script/2.velero--backup-and-restore/reconcile.sh $GITHUB_REPOSITORY
      - name: Velero Restore
        if: ${{ github.event.inputs.action == 'restore' }}
        run: |
          chmod +x "script/2.velero--backup-and-restore/restore.sh"
          ./script/2.velero--backup-and-restore/restore.sh "${{ github.event.inputs.restored_version }}"
